
services:
  divein-api:
    container_name: divein
    build: api
    volumes:
      # - .:/api
      # - ./app:/api/src/app
      # - .env:/api/.env
      # - /api/node_modules
      - ./api:/api
      - ./app:/api/app
      # - .env:/app/.env
      - /app/node_modules
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
    networks:
      - shared-network # for development
      - default
    # ports:
      # - "3000:3000"
    depends_on:
      - db

    restart: unless-stopped

  db:
    container_name: divein-db
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  db_data:

networks:
  shared-network:
    external: true
  default:
